
global:
  scrape_interval:     15s
  evaluation_interval: 15s
rule_files:
scrape_configs:
  - job_name: 'ic_prometheus'
    static_configs:
    - targets: ['ic_prometheus:9090']

  - job_name: 'ic_flask_api'
    scrape_interval: 5s
    static_configs:
    - targets: ['ic_flask_api:5000']